### PR TITLE
CUI32Stem configuration

### PR DESCRIPTION
**Pull request by majenkotech**
Another board whose default bootloader doesn't work in Linux - so here's a config for it.

### CODE REVIEW

**Comment by EmbeddedMan** [comment]
Matt, this PR apparently has conflicts. If you can resolve them, I'm happy to merge it in.

**Comment by majenkotech** [comment]
Umm... have you seen the date on this PR...?

**Comment by EmbeddedMan** [comment]
Should I just close it without merging? :-)

**Comment by majenkotech** [comment]
I'm thinking that might be the sensible option. We haven't missed having it in there, which means it's most likely obsolete.

**Comment by EmbeddedMan** [comment]
Closing this without merging it, cause good reasons.

**Pull request closed without merging**
