### PR TITLE
Add Microchip Starter Kit UART configuration.

### PR DESCRIPTION
**Pull request by crmoratelli**
Suggestion to add Microchip Starter Kit configuration files.

### CODE REVIEW

**Comment by davidbitton** [comment]
Which MPLAB X project configuration shall I use in order to compile for the Microchip Eth starter kit?

**Comment by EmbeddedMan** [comment]
Is this the PIC32MZ starter kit that you are referring to? That's the only one we have a separate bootloader build target for at the moment.

But it's very easy to get it going for other boards. What processors is on your kit?

**Comment by davidbitton** [comment]
I am referring to the [PIC32MZ Embedded Connectivity with FPU (EF) Starter Kit (Crypto)
Part Number: DM320007-C](http://tro.pe/2EJGIch). That board has a PIC32MZ2048EFM144 chip. I plan on using the 064 variant in the final product; 144 should be fine for development. The precompiled bootloader in this repo should suffice but I'll need to be able to make changes to the config  -- I think -- in order to use the 64 pin version in lieu of the 144 pin version. Thanks.

**Comment by EmbeddedMan** [comment]
OK, very good. Let me know if you run into trouble.

**Comment by davidbitton** [comment]
@EmbeddedMan will do, however which MPLAB config shall I use in order to compile the bootloader? Thanks.

**Comment by EmbeddedMan** [comment]
Hmmm. In looking at the commit referenced at the top of this thread, it
doesn't look like we actually added a new build configuration for this
board. The rest of the work seems to have been done, but the build
configuration is missing. I'll need to fix that tonight. I'll let you know
when it's in and builds.

**Comment by davidbitton** [comment]
Great. Appreciate that.

**Comment by davidbitton** [comment]
I see the config is setup to read from UART2 via the USB-to-UART chip. What is required in order for the bootloader to read from the internal USB module? Thanks.

**Comment by EmbeddedMan** [comment]
There's just a flag that you flip - if you want hardware serial, then
use  blCapUARTInterface
  , if you want built-in USB, use  blCapUSBInterface  .

Since I don't have one of these boards, you'll have to let me know what the
right values are for things like the config bits, oscillator settings, what
pin the push button is on, leds, etc.

**Comment by davidbitton** [comment]
@EmbeddedMan will do. It looks like the config for the Microchip board is there and correct. I'll make the changes as needed later down the road.

**Comment by EmbeddedMan** [comment]
davidbitton - I just merged https://github.com/chipKIT32/PIC32-avrdude-bootloader/pull/43 which (I hope) added a working build configuration for this board. Give it a try and see if I messed anything up.

**Comment by davidbitton** [comment]
Looks good.

```

CLEAN SUCCESSFUL (total time: 68ms)
make -f nbproject/Makefile-MICROCHIP_MZ_STARTER_KIT.mk SUBPROJECTS= .build-conf
make[1]: Entering directory '/Users/bittond/GoogleDrive/src/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X'
make  -f nbproject/Makefile-MICROCHIP_MZ_STARTER_KIT.mk dist/MICROCHIP_MZ_STARTER_KIT/production/chipKIT-Bootloaders.X.production.hex
make[2]: Entering directory '/Users/bittond/GoogleDrive/src/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X'
"/Applications/microchip/xc32/v2.05/bin/xc32-gcc" -c -mprocessor=32MZ2048EFM144 -MMD -MF build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/pic32_init_tlb_ebi_sqi.o.d -o build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/pic32_init_tlb_ebi_sqi.o ../pic32_init_tlb_ebi_sqi.S -DXPRJ_MICROCHIP_MZ_STARTER_KIT=MICROCHIP_MZ_STARTER_KIT -no-legacy-libc -ftoplevel-reorder -Wa,--defsym=__MPLAB_BUILD=1,-MD=build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/pic32_init_tlb_ebi_sqi.o.asm.d,--gdwarf-2 -DPIC32MZ -DINIT_MMU_MZ_FIXED -DINIT_SSX -DINIT_L1_CACHE -DINIT_DSPR2 -DPIC32_SRS_SET_COUNT=8 
"/Applications/microchip/xc32/v2.05/bin/xc32-gcc" -c -mprocessor=32MZ2048EFM144 -MMD -MF build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/crt0MZ.o.d -o build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/crt0MZ.o ../crt0MZ.S -DXPRJ_MICROCHIP_MZ_STARTER_KIT=MICROCHIP_MZ_STARTER_KIT -no-legacy-libc -ftoplevel-reorder -Wa,--defsym=__MPLAB_BUILD=1,-MD=build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/crt0MZ.o.asm.d,--gdwarf-2 -DPIC32MZ -DINIT_MMU_MZ_FIXED -DINIT_SSX -DINIT_L1_CACHE -DINIT_DSPR2 -DPIC32_SRS_SET_COUNT=8 
"/Applications/microchip/xc32/v2.05/bin/xc32-gcc" -c -mprocessor=32MZ2048EFM144 -MMD -MF build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/pic32_init_cache.o.d -o build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/pic32_init_cache.o ../pic32_init_cache.S -DXPRJ_MICROCHIP_MZ_STARTER_KIT=MICROCHIP_MZ_STARTER_KIT -no-legacy-libc -ftoplevel-reorder -Wa,--defsym=__MPLAB_BUILD=1,-MD=build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/pic32_init_cache.o.asm.d,--gdwarf-2 -DPIC32MZ -DINIT_MMU_MZ_FIXED -DINIT_SSX -DINIT_L1_CACHE -DINIT_DSPR2 -DPIC32_SRS_SET_COUNT=8 
"/Applications/microchip/xc32/v2.05/bin/xc32-gcc" -g -x c -c -mprocessor=32MZ2048EFM144 -D_BOARD_MICROCHIP_ETH_START_KIT_UART_ -I.. -MMD -MF build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/main.o.d -o build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/main.o ../main.c -DXPRJ_MICROCHIP_MZ_STARTER_KIT=MICROCHIP_MZ_STARTER_KIT -no-legacy-libc -ftoplevel-reorder 
"/Applications/microchip/xc32/v2.05/bin/xc32-gcc"   -mprocessor=32MZ2048EFM144 -nostdlib -nostartfiles -mno-float -o dist/MICROCHIP_MZ_STARTER_KIT/production/chipKIT-Bootloaders.X.production.elf build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/main.o build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/crt0MZ.o build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/pic32_init_cache.o build/MICROCHIP_MZ_STARTER_KIT/production/_ext/1472/pic32_init_tlb_ebi_sqi.o          -DXPRJ_MICROCHIP_MZ_STARTER_KIT=MICROCHIP_MZ_STARTER_KIT  -no-legacy-libc  -ftoplevel-reorder   -Wl,--defsym=__MPLAB_BUILD=1,--script="../MZ-boot-linkerscript.ld",--no-code-in-dinit,--no-dinit-in-serial-mem,-Map="dist/MICROCHIP_MZ_STARTER_KIT/production/chipKIT-Bootloaders.X.production.map",--memorysummary,dist/MICROCHIP_MZ_STARTER_KIT/production/memoryfile.xml
"/Applications/microchip/xc32/v2.05/bin"/xc32-bin2hex dist/MICROCHIP_MZ_STARTER_KIT/production/chipKIT-Bootloaders.X.production.elf 
Normalizing hex file
make[2]: Leaving directory '/Users/bittond/GoogleDrive/src/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X'
--------------------------------------
User defined post-build step: [cp dist/MICROCHIP_MZ_STARTER_KIT/production/chipKIT-Bootloaders.X.production.hex ../../BootloadersCurrent-hex/MICROCHIP_MZ_STARTER_KIT.hex]
--------------------------------------
make[1]: Leaving directory '/Users/bittond/GoogleDrive/src/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X'

BUILD SUCCESSFUL (total time: 1s)
Loading code from /Users/bittond/GoogleDrive/src/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X/dist/MICROCHIP_MZ_STARTER_KIT/production/chipKIT-Bootloaders.X.production.hex...
Loading completed
```

**Pull request merged**
